services:
  db:
    image: postgis/postgis
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: local
    volumes:
      - ./.env.db:/var/lib/postgresql/data

  martin:
    image: ghcr.io/maplibre/martin:latest
    restart: unless-stopped
    ports:
      - 3000:3000
    #command: --save-config config.yaml --default-srid=4326
    command: --config config.yaml
    volumes:
      - ./martin.yaml:/config.yaml
    environment:
      - DATABASE_URL=postgres://root:mysecretpassword@db:5432/local
    depends_on:
      - db
